name: bricks_and_cli

packages:
  - vyuh_cli

ide:
  intellij:
    moduleNamePrefix: ''

scripts:
  update_version:
    run: dart run tools/update_version.dart
  version:
    hook: pre
    run: melos run update_version

command:
  version:
    hooks:
      pre: melos run update_version