name: bricks

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^4.0.0
  melos: ^6.1.0
  pubspec_parse: ^1.3.0
  mason_logger: ^0.3.1

dependencies:
  flutter:
    sdk: flutter
